# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nixpkgs = {
    pname = "nixpkgs";
    version = "dc5d91f840324650bac8c379428c7037a416959a";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/dc5d91f840324650bac8c379428c7037a416959a.tar.gz";
      sha256 = "sha256-VaWGJ6+cIYN2erfSecbRV+4ljI185Ty2wUrXyvQbgOw=";
    };
    date = "2026-09-07";
  };
}
