# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nixpkgs = {
    pname = "nixpkgs";
    version = "26.11pre1062397.9fbb54b33e91";
    src = fetchTarball {
      url = "https://releases.nixos.org/nixos/unstable/nixos-26.11pre1062397.9fbb54b33e91/nixexprs.tar.zst";
      sha256 = "sha256-IkjmqLoWzeqBAi1VIkdhDLMGjQDJ4suEDp59Zwxpswg=";
    };
  };
}
